### PR TITLE
7  recipe detail

### PR DESCRIPTION
**Pull request by lianmccc**
recipe detail page UI layout

### CODE REVIEW

**Comment by JakinHuangWang** [comment]
Screen Shot 2021-02-13 at 4 28 01 AM

@lianmccc **search_results** page looks slightly weird on my laptop

**Comment by lianmccc** [comment]
> Screen Shot 2021-02-13 at 4 28 01 AM
> 
> @lianmccc **search_results** page looks slightly weird on my laptop

@JakinHuangWang search_results and my_recipe page are in branch 6--RecipeCollection, I checkout branch7 based on 6, should we merge branch6 first?

**Comment by JakinHuangWang** [comment]
@lianmccc That means the error comes from  6--RecipeCollection, it should be fixed before merge.

**Comment by lianmccc** [comment]
> @lianmccc That means the error comes from 6--RecipeCollection, it should be fixed before merge.

I think @spencer-jin has a fixed search_results and my_recipe page in 6--RecipeCollection.

**Review by spencer-jin — APPROVED** [review]

**Pull request merged**
